# **Carga de datos general**

Importacion de las bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
from google.colab import files
%matplotlib inline

Leer y guardar datos en un DataFrame

In [ ]:
uploaded = files.upload()
df = pd.read_csv('DIQ_J.csv')
df = df.fillna(0)
df3 = df
df.shape

Saving DIQ_J.csv to DIQ_J.csv


(8897, 55)

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['DIQ_J.csv']))

In [ ]:
df = pd.read_csv('DIQ_J.csv')
df = df.fillna(0)

In [ ]:
df.shape

(8897, 55)

Generar targets y data

In [ ]:
x = df.drop('DIQ010', axis=1)
y = df['DIQ010']

# **Support Vector Machines**

Generar los sets de entrenamiento y prueba

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
print("x_train : ",x_train.shape)

print("x_test : ",x_test.shape)

print("y_train : ",y_train.shape)

print("y_test : ",y_test.shape)

x_train :  (6227, 54)
x_test :  (2670, 54)
y_train :  (6227,)
y_test :  (2670,)


Entrena el modelo

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Genera una predicción

In [ ]:
y_pred = svclassifier.predict(x_test)
y_pred

array([1., 2., 1., ..., 2., 2., 2.])

Evalua el modelo

In [ ]:
score = svclassifier.score(x_test, y_test)
print(score)

0.9775280898876404


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 265    2    0    0]
 [   1 2345    0    0]
 [   0   54    0    0]
 [   0    2    1    0]]
              precision    recall  f1-score   support

         1.0       1.00      0.99      0.99       267
         2.0       0.98      1.00      0.99      2346
         3.0       0.00      0.00      0.00        54
         9.0       0.00      0.00      0.00         3

    accuracy                           0.98      2670
   macro avg       0.49      0.50      0.50      2670
weighted avg       0.96      0.98      0.97      2670



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Visualizar datos del test
pd.DataFrame(y_test)

DIQ010
5707     1.0
4764     2.0
3184     1.0
1091     2.0
994      2.0
...      ...
302      3.0
4441     2.0
5358     2.0
1790     2.0
5626     2.0

[2670 rows x 1 columns]

In [ ]:
#Visualizar datos de predicción
pd.DataFrame(y_pred, columns = ['DIQ010'])

DIQ010
0        1.0
1        2.0
2        1.0
3        2.0
4        2.0
...      ...
2665     2.0
2666     2.0
2667     2.0
2668     2.0
2669     2.0

[2670 rows x 1 columns]

# **Regresión Logística**

Carga el modelo y genera los sets de entrenamiento y prueba

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
print("x_train : ",x_train.shape)

print("x_test : ",x_test.shape)

print("y_train : ",y_train.shape)

print("y_test : ",y_test.shape)

x_train :  (6672, 54)
x_test :  (2225, 54)
y_train :  (6672,)
y_test :  (2225,)


Entrena el modelo

In [ ]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Predice con el modelo

In [ ]:
pred = logisticRegr.predict(x_test)
pred

array([1., 2., 1., ..., 2., 2., 2.])

Evalua el modelo

In [ ]:
score = logisticRegr.score(x_test, y_test)
print(score)

0.9793258426966293


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[ 219    2    0    0]
 [   1 1960    0    0]
 [   0   42    0    0]
 [   0    1    0    0]]
              precision    recall  f1-score   support

         1.0       1.00      0.99      0.99       221
         2.0       0.98      1.00      0.99      1961
         3.0       0.00      0.00      0.00        42
         9.0       0.00      0.00      0.00         1

    accuracy                           0.98      2225
   macro avg       0.49      0.50      0.50      2225
weighted avg       0.96      0.98      0.97      2225



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Visualizar datos del test
pd.DataFrame(y_test)

DIQ010
5707     1.0
4764     2.0
3184     1.0
1091     2.0
994      2.0
...      ...
191      2.0
8808     2.0
530      2.0
5894     2.0
2685     2.0

[2225 rows x 1 columns]

In [ ]:
#Visualizar datos de predicción
pd.DataFrame(pred, columns = ['DIQ010'])

DIQ010
0        1.0
1        2.0
2        1.0
3        2.0
4        2.0
...      ...
2220     2.0
2221     2.0
2222     2.0
2223     2.0
2224     2.0

[2225 rows x 1 columns]

# **Árboles de Decisión**

Importamos las librerias que utilizaremos.


In [ ]:
from sklearn import preprocessing
from sklearn import tree
from IPython.display import Image
import pydotplus
import io
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from sklearn import metrics

In [ ]:
df2 = pd.read_csv('DIQ_J.csv')
df2 = df2.fillna(0)

In [ ]:
df2.head()

Unnamed: 0     SEQN  DIQ010  DID040  ...  DID350  DIQ350U  DIQ360  DIQ080
0           0  93703.0     2.0     0.0  ...     0.0      0.0     0.0     0.0
1           1  93704.0     2.0     0.0  ...     0.0      0.0     0.0     0.0
2           2  93705.0     2.0     0.0  ...     0.0      0.0     0.0     0.0
3           3  93706.0     2.0     0.0  ...     0.0      0.0     0.0     0.0
4           4  93707.0     2.0     0.0  ...     0.0      0.0     0.0     0.0

[5 rows x 55 columns]

Primero dividimos nuestra informacion en el grupo de informacion que se utilizara para hacer la prediccion y lo que queremos predeccir. Tambien hacemos un poco de preprocessing.

In [ ]:
X = df2.drop('DIQ010', axis=1)
Y = df2['DIQ010']

#Hacemos training sets para dividir nuestra informacion de manera aleatoria y entrenar nuestro algoritmo.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

#Utilizamos el mdelo de fit para hacer un arbol de decision
classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

Hacemos una prediccion con la data de practica.

In [ ]:
y_pred = classifier.predict(X_test)

Evaluamos el algoritmo.

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[ 179    0    2    0]
 [   0 1558    0    2]
 [   0    0   39    0]
 [   0    0    0    0]]
              precision    recall  f1-score   support

         1.0       1.00      0.99      0.99       181
         2.0       1.00      1.00      1.00      1560
         3.0       0.95      1.00      0.97        39
         9.0       0.00      0.00      0.00         0

    accuracy                           1.00      1780
   macro avg       0.74      0.75      0.74      1780
weighted avg       1.00      1.00      1.00      1780



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
rf = RandomForestClassifier(n_estimators=100,
                            random_state=0)
rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

Ahora hacemos el arbol una imagen visible.

Hacemos una funcion que nos grafique el arbol, en caso de que nos llame un error por nuestros target_names o que nuestro indice esta fuera, cambiar el numero en rf.estimators_[] a uno que sea mayor por 1.

In [ ]:
def printTree(classifier):
    feature_names = dn
    target_names = ['1', '2', '3']
    # Build the data
    dot_data = tree.export_graphviz(classifier, out_file=None,
                                    feature_names=feature_names)
    # Build the graph
    graph = pydotplus.graph_from_dot_data(dot_data)

    # Show the image
    Image(graph.create_png())
    graph.write_png("tree.png")

In [ ]:
dn = ['SEQN','DIQ010','DID040','DIQ160','DIQ170','DIQ172','DIQ175A','DIQ175B','DIQ175C','DIQ175D','DIQ175E','DIQ175F','DIQ175G','DIQ175H','DIQ175I','DIQ175J','DIQ175K','DIQ175L','DIQ175M','DIQ175N','DIQ175O','DIQ175P','DIQ175Q','DIQ175R','DIQ175S','DIQ175T','DIQ175U','DIQ175V','DIQ175W','DIQ175X','DIQ180','DIQ050','DID060','DIQ060U','DIQ070','DIQ230','DIQ240','DID250','DID260','DIQ260U','DIQ275','DIQ280','DIQ291','DIQ300S','DIQ300D','DID310S','DID310D','DID320','DID330','DID341','DID350','DIQ350U','DIQ360','DIQ080']

In [ ]:
printTree(rf.estimators_[0])

In [ ]:
#funcion extra, otra manera de hacerlo.
# cn = ['1','2','3']
# fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=800)
# tree.plot_tree(rf.estimators_[0],
#                feature_names = dn,
#                filled = False);
# fig.savefig('rf_individualtree.png')

Como podemos observar, como en nuestra informacion no tenemos ninguna columna que sea igual a algun nombre como tener o no tener diabetes, por lo que tenemos que dejar el arbol de forma visual como algo no viable.

Ahora vemos cual es la precision de nuestro modelo.

In [ ]:
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred))

Accuracy: 0.9977528089887641


# **Naïve Bayes classifiers**

Importamos las librerias que vamos a utilizar.

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

Creamos la informacion.

In [ ]:
columns = ['Unnamed: 0', 'SEQN', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172',
       'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F',
       'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L',
       'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R',
       'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X',
       'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240',
       'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S',
       'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350',
       'DIQ350U', 'DIQ360', 'DIQ080']
data = df3
target = df3['DIQ010']
X_train, X_test, y_train, y_test = train_test_split(df3, target, test_size=0.3,random_state=109) # 70% training and 30% test

Generamos el modelo

In [ ]:
#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

Observamos la presicion del modelo.

In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9921348314606742
